# Generated by Django 4.2 on 2023-07-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('product', '0003_productstoreinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stores'
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(through='product.ProductStoreInfo', to='stores.store')
        )
    ]
