# Generated by Django 4.2.3 on 2023-07-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_trigram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstoreinfo',
            options={'ordering': ['price']},
        ),
    ]
