# Generated by Django 4.2.3 on 2023-08-06 20:32

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("order", "Order")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_uuid'),
    ]

    operations = [
         migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
