# Generated by Django 4.2.3 on 2023-08-08 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('order', '0004_alter_order_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='store_id',
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.CharField(default='ur mom', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='smd', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=69.69, max_digits=6),
            preserve_default=False,
        ),
    ]
