# Generated by Django 4.2.3 on 2023-08-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderitem_product_name_orderitem_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Processing', max_length=10),
        ),
    ]
