# Generated by Django 4.2.3 on 2023-08-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderitem_store_id_order_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Awaiting Payment', max_length=10),
        ),
    ]
