# Generated by Django 4.2.3 on 2023-10-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('a', 'Awaiting Payment'), ('p', 'Pending'), ('o', 'Out for Delivery'), ('d', 'Delivered'), ('c', 'Cancelled')], default='a', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
