# Generated by Django 4.2.7 on 2024-01-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_delivery_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_distance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
